### ISSUE TITLE
Testing review.  Make sure the code is fully exercised.

### ISSUE THREAD

**Issue by gregseb** [pauperpythonistas/python-geomark#16]
Need more robust testing.  See the django-rest-framework-gis repo for examples.  The tests should run in a series.  The first test will be for geomark creation, and if it passes, the results will be used in subsequent tests to check that they return the exact results we expect.

We should test that we correctly implement every feature, including all available functions, and our ability to provide and request all available data formats and projections.

**Comment by spatialbits** [comment]
We've got some basic tests for create/copy that use kml file fixtures. We could add geojson versions of the kml files to the tests as well.

**Comment by gregseb** [comment]
Forgot to reference this issue in PR #29   Closing.
