### ISSUE TITLE
Should we keep testing properties?

### ISSUE THREAD

**Issue by gregseb** [pauperpythonistas/python-geomark#32]
Main upside is its nice to see that we're getting the **exact** response we expect.

Main downside is that we have already had experience with inconsistent results from Geomark properties, especially after they update their service.  On the other hand, it shouldn't be too hard to keep an eye on their newsletters and updates to be prepared for such a thing.

**Comment by spatialbits** [comment]
My feeling is they're not essential, but I think if they're in and working they might as well be left put. 
The day the tests start breaking we can decide if these are needed.
